enum MessageType : byte
{
    Acknowledge,
    Greetings,
    PlayerPosition,
    GameInfo,
	PlayerAim,
	PlayerAction,
	PlayerItemAction,
	TextMessage,
	SpawnedProjectile,
	Spawned,
	ObjectUpdate,
	RemoteCommand,
	Damaged,
	MarkedForDeletion,
	ObjectKilled,
	PlayerShoot
}