name: Build for windows

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ pipeline ]

env:
  runtime: win-x64
  configuration: Release
   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: TEMP TEST
      run: echo do these environment variables work ? ${{runtime}}

    - name: Build
      run: dotnet publish -p:Configuration=$configuration -p:r=${{runtime}} -p:PublishSingleFile=true
      
    - name: Remove debug files
      run: rm ./build/*.pdb
      
    - name: Remove jsons
      run: rm ./build/*.json
      
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release.exe
        path:  ./build
        retention-days: 5
