name: Build windows v4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish /p:Configuration=Release /p:PublishProfile=FolderProfile
      
    - uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        directory: ./TheForestWaiter/bin/Release/net5.0/publish/
        exclusions: '*.pdb'
        
    - name: Publish-Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release.zip
        path:  release.zip
        retention-days: 5
